export const ROUTE_NAME = {
  AUTHENTICATION: 'AUTHENTICATION',
  ROLESELECT: 'ROLESELECT',
  INTRODUCTION: 'INTRODUCTION',
  ONBOARDING: 'ONBOARDING',
  MY_TABS: 'MY_TABS',
  HOME_TAB: 'HOME_TAB',
  APPILIED_TAB: 'APPILIED_TAB',
  MY_JOB_TAB: 'MY_JOB_TAB',
  PROFILE_TAB: 'PROFILE_TAB',
  JOB_DETAILS: 'JOB_DETAILS',
  SEARCH_RESULT: 'SEARCH_RESULT',
};
