export const TEXT = {
  HELLO_THERE: 'Hello there,',
  CONT_MOBILE_NO: "Let's continue with\nMobile number",
  MOBILE_NO: 'Mobile number',
  LET_VERIFY: "Let's verify",
  CONT_LET_VERIFY: "Let's verify your mobile number",
  CHANGE_TXT: 'Change',
  VERIFY_CODE: 'Verification Code',
  VERIFY: 'Verify',
  LET_LOGIN: "Let's Login",
  EMAIL: 'Email',
  PASSWORD: 'Password',
  TERM_CONDITION: 'By clicking you are agreeing to\nKisangates',
  TERM_N_CONDITION: 'Term & Conditions ',
  PRIVACY_POLICY: 'Privacy Policy',
  FORGOT_PASSWORD: 'Forgot Password?',
  HELP_ME_BUILD: 'Help me build your\nProfile',
  HEY_IM: "Hey, I'm Simran",
  PERSONAL_ASSIGTANT: 'Your, Personal Assistant',
  SKIP: 'Skip',
  BUILD_PROFILE: "Let's build your Profile",
  WHAT_I_CALL: 'What should I call you?',
  NAME: 'Name',
  ENTER_NAME: 'Enter your Name',
  SHARE_PHONE_NO: 'Please share your\nPhone Number',
  PHONE_NUMBER: 'Phone Number',
  STATE_DISTRICT: 'Select your\nState and District',
  TAP_TO_SELECT: 'Tap me to select the\nstate and district',
  SELECT_STATE: 'Select the State',
  SELECT_DISTRICT: 'Select the District',
  SEARCH: 'Search',
  NEXT: 'Next',
  SELECT: 'Select',
  INTERESTED_SEGMENTS: 'Select your\nInterested Segements',
  EXPERIENCE: 'Select your\nExperience',
  PREVIOUS_WORKED: 'Select your\nPrevious worked crops',
  WELCOME: 'Welcome',
  RECENT_LIST: 'Recent Listings',
  CHECKOUT_LIST: 'Hey checkout latest jobs',
  CLEAR_ALL: 'Clear all',
  HEY_YOU_CAN: 'Hey, you can',
  FILTER: 'Filter',
  JOB_DETAILS: 'Job Details',
  CLOSING_DATE: 'Closing Date',
  FULL_TIME: 'Full Time',
  LOCATION: 'Location',
  COMPANY: 'Company',
  JOB_DESCRIPTION: 'Job Description',
  APPLY: 'Apply',
  EXTRA_QUES: 'Extra question will\nBe asking here',
  SEARCH_RESULT: 'Search result',
  SEARCH_KEYWORD: 'Search keyword',
  APPLIED_JOB: 'Applied Jobs',
  APPLIED_JOB_LINE: 'Hey checkout latest jobs',
  MY_JOB: 'My Jobs',
  MY_JOB_LINE: 'Hey checkout your jobs',
  ACTIVE: 'Active',
  COMPLETED: 'Completed',
  EDIT: 'Edit',
  PERSONAL_INFO: 'Personal Info',
  PROFESSIONAL_INFO: 'Professional Info',
  GENDER: 'Gender',
  STATE_LOCATION: 'State & Location',
  INTERESTED_SEGMENTS_TEXT: 'Interested Segments',
  EXPERIENCE_TEXT: 'Experience',
  PREVIOUS_WORKED_CROP: 'Previous worked crops',
  UPDATE: 'Update',
  APPLIED_ON: 'Applied on',
  STATUS: 'Status',
};
